# typed: false
# frozen_string_literal: true

# This file was generated by GoReleaser. DO NOT EDIT.
class Lazyopenconnect < Formula
  desc "TUI for managing OpenConnect VPN connections"
  homepage "https://github.com/Nybkox/lazyopenconnect"
  version "0.3.1"
  license "MIT"

  on_macos do
    if Hardware::CPU.intel?
      url "https://github.com/Nybkox/lazyopenconnect/releases/download/v0.3.1/lazyopenconnect_0.3.1_darwin_amd64.tar.gz"
      sha256 "32d37513deb4dbdc2d1dedd8b97bcac12b51c6537360c60bb1840c4b78e6c536"

      def install
        bin.install "lazyopenconnect"
      end
    end
    if Hardware::CPU.arm?
      url "https://github.com/Nybkox/lazyopenconnect/releases/download/v0.3.1/lazyopenconnect_0.3.1_darwin_arm64.tar.gz"
      sha256 "325c3a6c44230c8f349d2c8510f9cb7c368044dd5c2e99fa612bbe0089680e16"

      def install
        bin.install "lazyopenconnect"
      end
    end
  end

  on_linux do
    if Hardware::CPU.intel? && Hardware::CPU.is_64_bit?
      url "https://github.com/Nybkox/lazyopenconnect/releases/download/v0.3.1/lazyopenconnect_0.3.1_linux_amd64.tar.gz"
      sha256 "db55173abdc331ab3ec68f3d223ab6c7f251654edc27688163d46d93fce8ace4"
      def install
        bin.install "lazyopenconnect"
      end
    end
    if Hardware::CPU.arm? && Hardware::CPU.is_64_bit?
      url "https://github.com/Nybkox/lazyopenconnect/releases/download/v0.3.1/lazyopenconnect_0.3.1_linux_arm64.tar.gz"
      sha256 "5c6aae5c7b5a8b47edff222af20cdc808c4e7faaf9df3242b9d66e1be75cb31f"
      def install
        bin.install "lazyopenconnect"
      end
    end
  end

  def post_install
    config_dir = "#{Dir.home}/.config/lazyopenconnect"
    system "mkdir", "-p", config_dir
    marker = "#{config_dir}/.installed-by"
    File.write(marker, <<~EOS)
      method=homebrew
      path=#{bin}/lazyopenconnect
      version=#{version}
      date=#{Time.now.strftime('%Y-%m-%d')}
    EOS
  end

  test do
    system "#{bin}/lazyopenconnect", "--version"
  end
end
