# typed: false
# frozen_string_literal: true

# This file was generated by GoReleaser. DO NOT EDIT.
class Lazyopenconnect < Formula
  desc "TUI for managing OpenConnect VPN connections"
  homepage "https://github.com/Nybkox/lazyopenconnect"
  version "0.2.0"
  license "MIT"

  on_macos do
    if Hardware::CPU.intel?
      url "https://github.com/Nybkox/lazyopenconnect/releases/download/v0.2.0/lazyopenconnect_0.2.0_darwin_amd64.tar.gz"
      sha256 "0e1cbf78288710e72f0faf6436f74a874042e1d094793e808a7c9d115dad23f8"

      def install
        bin.install "lazyopenconnect"
      end
    end
    if Hardware::CPU.arm?
      url "https://github.com/Nybkox/lazyopenconnect/releases/download/v0.2.0/lazyopenconnect_0.2.0_darwin_arm64.tar.gz"
      sha256 "ba7929b7d3c800e508ad90dc7eacddcde3ab085a4dace3bd4126b968f999352a"

      def install
        bin.install "lazyopenconnect"
      end
    end
  end

  on_linux do
    if Hardware::CPU.intel? && Hardware::CPU.is_64_bit?
      url "https://github.com/Nybkox/lazyopenconnect/releases/download/v0.2.0/lazyopenconnect_0.2.0_linux_amd64.tar.gz"
      sha256 "7a98ba048fb799d9a56c1e64f77d7f0421a32d647f57540552e23b4e2427d134"
      def install
        bin.install "lazyopenconnect"
      end
    end
    if Hardware::CPU.arm? && Hardware::CPU.is_64_bit?
      url "https://github.com/Nybkox/lazyopenconnect/releases/download/v0.2.0/lazyopenconnect_0.2.0_linux_arm64.tar.gz"
      sha256 "5d063540201d3cbedc90bcce3a032688d423b0e7b1cf7a7d4026db91ea00ffc2"
      def install
        bin.install "lazyopenconnect"
      end
    end
  end

  def post_install
    config_dir = "#{Dir.home}/.config/lazyopenconnect"
    system "mkdir", "-p", config_dir
    marker = "#{config_dir}/.installed-by"
    File.write(marker, <<~EOS)
      method=homebrew
      path=#{bin}/lazyopenconnect
      version=#{version}
      date=#{Time.now.strftime('%Y-%m-%d')}
    EOS
  end

  test do
    system "#{bin}/lazyopenconnect", "--version"
  end
end
