# typed: false
# frozen_string_literal: true

# This file was generated by GoReleaser. DO NOT EDIT.
class Lazyopenconnect < Formula
  desc "TUI for managing OpenConnect VPN connections"
  homepage "https://github.com/Nybkox/lazyopenconnect"
  version "0.5.1"
  license "MIT"

  on_macos do
    if Hardware::CPU.intel?
      url "https://github.com/Nybkox/lazyopenconnect/releases/download/v0.5.1/lazyopenconnect_0.5.1_darwin_amd64.tar.gz"
      sha256 "981395f3a82764d46fca74832d5e20042c7dd0d81c5b000f8b96f21475961726"

      def install
        bin.install "lazyopenconnect"
      end
    end
    if Hardware::CPU.arm?
      url "https://github.com/Nybkox/lazyopenconnect/releases/download/v0.5.1/lazyopenconnect_0.5.1_darwin_arm64.tar.gz"
      sha256 "7f5b95ced2beb20bc0385f9781cb53ce6f72cf0c41aeeaefe70007ee86597fac"

      def install
        bin.install "lazyopenconnect"
      end
    end
  end

  on_linux do
    if Hardware::CPU.intel? && Hardware::CPU.is_64_bit?
      url "https://github.com/Nybkox/lazyopenconnect/releases/download/v0.5.1/lazyopenconnect_0.5.1_linux_amd64.tar.gz"
      sha256 "acaec8193998368e515c2bcd052d3c94deddc345ad770e696fab8d0deebe1715"
      def install
        bin.install "lazyopenconnect"
      end
    end
    if Hardware::CPU.arm? && Hardware::CPU.is_64_bit?
      url "https://github.com/Nybkox/lazyopenconnect/releases/download/v0.5.1/lazyopenconnect_0.5.1_linux_arm64.tar.gz"
      sha256 "855a56df7260cb11abf14c5960d3ff466fae7fb407e299add0ee4fb490695021"
      def install
        bin.install "lazyopenconnect"
      end
    end
  end

  def post_install
    config_dir = "#{Dir.home}/.config/lazyopenconnect"
    system "mkdir", "-p", config_dir
    marker = "#{config_dir}/.installed-by"
    File.write(marker, <<~EOS)
      method=homebrew
      path=#{bin}/lazyopenconnect
      version=#{version}
      date=#{Time.now.strftime('%Y-%m-%d')}
    EOS
  end

  test do
    system "#{bin}/lazyopenconnect", "--version"
  end
end
